sudo: required
services:
  - docker
  
before_install:
  - docker build -t bradwtracy/docker-react -f Dockerfile.dev .
  
script:
  - docker run -e CI=true bradwtracy/docker-react npm run test
  
deploy:
  provider: elasticbeanstalk
  region: "us-east-2"
  app: "btracy_docker-react"
  env: "BtracyDockerReact-env"
  bucket_name: "elasticbeanstalk-us-east-2-660694857359"
  bucket_path: "btracy_docker-react"
  on:
    branch: master
  access_key_id: $AWS_AK
  secret_access_key: $AWS_SK